### ISSUE TITLE
Breaking changes

### ISSUE THREAD

**Issue by chiendo97** [wrfly/ecp#15]
Since you delete the old function `Default` without a new version `v2`, some of our components got errors because it thinks the latest version should have `Default` func. 
https://github.com/wrfly/ecp/commit/78d8753b4bffb6f39b86460b2ccd1285eaa0d9c2#diff-dab1fc1f992d61bda5318058e8b8a7aad92caaebf219c1d3d489487b20dce4aaL125
For example: 
```
repo@version/file.go:XX:Y: undefined: ecp.Default
```

Suggestions: 
* Revert `Default` func back with `deprecated` message. 
* Bump to next version `v1`.

**Comment by wrfly** [comment]
Can you update your API?
